#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example:
          {
            "message": "Bad Request"
          }
  
  405:
    body:
      application/json:
        example:
          {
            "message": "Method not allowed"
          }

  500:
    body:
      application/json:
        example:
          {
            "message": "Internal Server Error"
          }