#%RAML 1.0
title: facebook-api
version: v1
protocols: [HTTP, HTTPS]
mediaType: [application/json]
description: "Created a facebook account"
traits:
  codes: !include /traits/trait.raml
/create_fb:
  post:
    is: [codes]
    body:
      type: !include /datatypes/dataType.raml
      example: !include /examples/account_request.json
    responses:
      201:
        body:
          example: !include /examples/account_response.json