#%RAML 1.0 Trait

queryParameters:
      number1:
        required: true
        type: number
      number2:
        required: true
        type: number

responses:
  400:
    body:
      application/json:
        example:
          {
            "message": "bad request"
          }
  
  404:
    body:
      application/json:
        example:
          {
            "message": "id not found"
          }

  405:
      body:
        application/json:
          example:
            {
              "message": "method not found"
            }

  500:
    body:
      application/json:
        example:
          {
            "message": "internal server error"
          }