#%RAML 1.0
title: acme-api
version: 1.0

/order:
  post:
    body:
      application/xml:
        example:
          <order oid="1001">
            <customerName>Annie Point</customerName>
            <itemName>Electric Standard Desk</itemName>
            <cost>300.00</cost>
          </order>